//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matechco
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public int user_sk { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string UserFullName { get; set; }
        public string email { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
    }
}
